name: firmware-STM32 build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get prequisites
      run: sudo apt update && sudo apt install -y --no-install-recommends gcc-avr gcc-arm-none-eabi build-essential avr-libc libc6-dev libnewlib-arm-none-eabi
    - name: CMake
      run: cmake .
      working-directory: firmware-STM32 
    - name: Make
      run: make 
      working-directory: firmware-STM32 
